CREATE TABLE "users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "artists" (
  "artist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "country" varchar
);

CREATE TABLE "albums" (
  "album_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "release_date" date,
  "artist_id" int NOT NULL
);

CREATE TABLE "songs" (
  "song_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar NOT NULL,
  "duration" int NOT NULL,
  "album_id" int NOT NULL
);

CREATE TABLE "genres" (
  "genre_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL
);

CREATE TABLE "song_genres" (
  "song_id" int NOT NULL,
  "genre_id" int NOT NULL,
  PRIMARY KEY ("song_id", "genre_id")
);

CREATE TABLE "playlists" (
  "playlist_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "playlist_songs" (
  "playlist_id" int NOT NULL,
  "song_id" int NOT NULL,
  "added_at" timestamp DEFAULT (now()),
  PRIMARY KEY ("playlist_id", "song_id")
);

CREATE UNIQUE INDEX ON "playlists" ("user_id", "name");

COMMENT ON COLUMN "songs"."duration" IS 'Duration in seconds';

ALTER TABLE "albums" ADD FOREIGN KEY ("artist_id") REFERENCES "artists" ("artist_id");

ALTER TABLE "songs" ADD FOREIGN KEY ("album_id") REFERENCES "albums" ("album_id");

ALTER TABLE "song_genres" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("song_id");

ALTER TABLE "song_genres" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("genre_id");

ALTER TABLE "playlists" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("user_id");

ALTER TABLE "playlist_songs" ADD FOREIGN KEY ("playlist_id") REFERENCES "playlists" ("playlist_id");

ALTER TABLE "playlist_songs" ADD FOREIGN KEY ("song_id") REFERENCES "songs" ("song_id");
